services:
  postgis-db:
    image: postgis/postgis
    container_name: clioguesser-db
    environment:
      POSTGRES_DB: clioguesser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clioguesser-net

  backend-api:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DB_NAME: clioguesser
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_HOST: localhost
        DB_PORT: 5432
    container_name: clioguesser-backend
    ports:
      - "7000:7000"
    env_file:
      - ./.env
    volumes:
      - ./clioguesser_backend/clioguesser_backend:/app/clioguesser_backend/clioguesser_backend
      - ./clioguesser_backend/manage.py:/app/clioguesser_backend/manage.py
      - ./clioguesser_backend/core:/app/clioguesser_backend/core
    depends_on:
      - postgis-db
    networks:
      - clioguesser-net
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py populate_cliopatria data/cliopatria_polities_only.geojson &&
             python3 manage.py runserver 0.0.0.0:7000"

volumes:
  postgres_data:

networks:
  clioguesser-net:
    name: clioguesser-net
    driver: bridge
    external: true
