services:
  postgis-db:
    image: postgis/postgis:15-3.3
    container_name: clioguesser-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: clioguesser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clioguesser-net

  frontend-api:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DB_NAME: clioguesser
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_HOST: localhost
        DB_PORT: 5432
    container_name: clioguesser-backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./clioguesser_backend:/app/clioguesser_backend
    depends_on:
      - postgis-db
    networks:
      - clioguesser-net
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py populate_cliopatria data/cliopatria_polities_only.geojson &&
             python3 manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:

networks:
  clioguesser-net:
    name: clioguesser-net
    driver: bridge
