# Generated by Django 4.0.3 on 2025-06-09 12:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliopatria",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "simplified_geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                ("name", models.CharField(max_length=100)),
                ("wikipedia_name", models.CharField(max_length=100, null=True)),
                ("seshat_id", models.CharField(max_length=100)),
                ("area", models.FloatField()),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField()),
                ("polity_start_year", models.IntegerField()),
                ("polity_end_year", models.IntegerField()),
                ("colour", models.CharField(max_length=7)),
                ("components", models.CharField(max_length=500, null=True)),
                ("member_of", models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
