# Generated by Django 4.0.3 on 2025-06-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliopatria',
            name='colour',
        ),
    ]
