# Generated by Django 4.0.3 on 2025-06-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_cliopatria_colour"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliopatria",
            name="polity_end_year",
        ),
        migrations.RemoveField(
            model_name="cliopatria",
            name="polity_start_year",
        ),
    ]
