# Generated by Django 4.0.3 on 2025-06-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_cliopatria_polity_end_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliopatria",
            name="simplified_geom",
        ),
    ]
