# Generated by Django 4.0.3 on 2025-06-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_cliopatria_simplified_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliopatria',
            name='polity_end_year',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliopatria',
            name='polity_start_year',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
